from sqlalchemy import Float, Integer, String
from sqlalchemy.event import listens_for
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


class IndividualCB(Base):
    __tablename__ = 'INDIVIDUAL_CB'

    STDT: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ID: Mapped[str] = mapped_column(String, primary_key=True)
    GENDER: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AGE_BAND: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1Z001373: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1M2B4W03: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1M2B5W03: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1Z001386: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1M210000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1M210001: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1M210003: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1M210006: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1811J001: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1811J003: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1811J006: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C18210000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C18233002: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C18233003: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C18233004: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C18233005: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120001: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120003: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120004: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120012: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120017: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120024: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120032: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120041: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120049: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120082: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120084: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120161: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120163: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120167: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120168: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120169: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120170: Mapped[int | None] = mapped_column(Integer, nullable=True)
    C1L120171: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120179: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120196: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120237: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120242: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120250: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120251: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120270: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120272: Mapped[float | None] = mapped_column(Float, nullable=True)
    C1L120292: Mapped[float | None] = mapped_column(Float, nullable=True)
    L10173000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10210000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10210001: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10210002: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10210003: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10210006: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L1021000C: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L1021000F: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L1021001P: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L1021003P: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L1021006P: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L1021009P: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L102100CP: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L1Z001044: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L90210100: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L90210200: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L90210300: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10210500: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10210800: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10210B00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10210M00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10216000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L90216100: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L90216106: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L90216200: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L90216300: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L90216306: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L90216700: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10216800: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10216806: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10216B00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10216M00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10217000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10217800: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10217B00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10218800: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10218B00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L1021A000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10220000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10220800: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10220806: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L1022080C: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10220B00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10220M00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10226800: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10226B00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10226M00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L1022A000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    L10231000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    U81102010: Mapped[int | None] = mapped_column(Integer, nullable=True)
    U81103010: Mapped[str | None] = mapped_column(String(50), nullable=True)
    U81201010: Mapped[int | None] = mapped_column(Integer, nullable=True)
    U81202010: Mapped[int | None] = mapped_column(Integer, nullable=True)
    U81203010: Mapped[int | None] = mapped_column(Integer, nullable=True)
    U81204010: Mapped[int | None] = mapped_column(Integer, nullable=True)
    U81205010: Mapped[str | None] = mapped_column(String(50), nullable=True)
    U81301010: Mapped[int | None] = mapped_column(Integer, nullable=True)
    U81302010: Mapped[int | None] = mapped_column(Integer, nullable=True)
    U81303010: Mapped[str | None] = mapped_column(String(50), nullable=True)
    U81304010: Mapped[str | None] = mapped_column(String(50), nullable=True)
    U81305010: Mapped[int | None] = mapped_column(Integer, nullable=True)
    U81306010: Mapped[int | None] = mapped_column(Integer, nullable=True)
    U10000002: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10110000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10110001: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10110003: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10110006: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D1011000C: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D1011000F: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10133000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10133001: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10133003: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10133006: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10133800: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D1013380F: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D1013A000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D1013A006: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D1013A00I: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D1013A00N: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D1013A00T: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10142D0I: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10142D0K: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10142D0N: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10142D0T: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10147000: Mapped[float | None] = mapped_column(Float, nullable=True)
    D10155000: Mapped[float | None] = mapped_column(Float, nullable=True)
    D10175000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10210D00: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10220000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10232000: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10232001: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10232003: Mapped[int | None] = mapped_column(Integer, nullable=True)
    D10232006: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AL012G005: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AL012G011: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AL012G019: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AL0C00001: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AL0C00002: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AL0C00003: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AL0C00004: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AL0C00005: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AP0910001: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AP0910002: Mapped[int | None] = mapped_column(Integer, nullable=True)
    AS120G001: Mapped[int | None] = mapped_column(Integer, nullable=True)
    SCORE: Mapped[int | None] = mapped_column(Integer, nullable=True)
    SCORE_6M: Mapped[int | None] = mapped_column(Integer, nullable=True)
    PERF1: Mapped[int | None] = mapped_column(Integer, nullable=True)
    PERF2: Mapped[int | None] = mapped_column(Integer, nullable=True)
    PERF3: Mapped[int | None] = mapped_column(Integer, nullable=True)
    PERF4: Mapped[int | None] = mapped_column(Integer, nullable=True)

    def __repr__(self) -> str:
        return f'IndividualCb(ID={self.ID!r}, STDT={self.STDT!r})'


@listens_for(IndividualCB, 'before_insert', propagate=True)
@listens_for(IndividualCB, 'before_update', propagate=True)
def preprocess(mapper, connection, target):
    pass


@listens_for(IndividualCB, 'load', propagate=True)
def postprocess(target, context):
    pass
